name = "jira-khanom"
compatibility_date = "2025-02-13"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "./dist"

[[d1_databases]]
binding = "DB"
database_name = "jira-khanom-db"
database_id = "4e6a9513-20b5-4b30-a185-07d771227442"
migrations_dir = "./migrations"

[vars]
WHATSAPP_TO = "+66 90 249 0306"
RESTAURANT_NAME = "Bottega Jira"
RESTAURANT_TIMEZONE = "Asia/Bangkok"
